### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by scuttle130** [james7780/5200BAS_python#1]
Thank you so much for creating a compiler to use 5200bas for MacOS!  Below is error message I am getting from trying to compile the basic hello.bas file.  Can you help me with what I might be doing wrong?  I included an "ls" of all the files in the main directory.  Thank you!

(base) Montos-MacBook-Air:5200BAS_python-master monto$ ls
5200BAS possible improvements.txt	basic documentation
5200bas-sources.zip			dasm.exe
5200bask.bas				examples
5200bask.py				go.bat
5200basl.bas				hello.bas
5200basl.py				helloworld.bas
ASCIISET.INC				inc
EQUATES.INC				pm.bas
HEADER.INC				readme.txt
How it works.txt
(base) Montos-MacBook-Air:5200BAS_python-master monto$ python 5200basl.py /D hello.bas
5200BAS Basic Compiler, version 1.97.  Copyright 2001-2002 by Jeffry Johnston.

Compiling 32k ROM for DASM 2.12
Input file  :  hello.bas 
Output file :  hello.ASM
Pre-include :  hello.2
Post-include:  hello.1
Traceback (most recent call last):
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2523, in <module>
    result, asmFileName = main(args)
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 198, in main
    inFile = open(inFileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'hello.bas '
(base) Montos-MacBook-Air:5200BAS_python-master monto$

**Comment by james7780** [comment]
Looking at the error: "FileNotFoundError: [Errno 2] No such file or directory: 'hello.bas ' 
It looks like you typed an extra space after hello.bas when entering the command.


    On Thursday, September 14, 2023 at 05:54:02 AM GMT+2, scuttle130 ***@***.***> wrote:  
 
 


Thank you so much for creating a compiler to use 5200bas for MacOS! Below is error message I am getting from trying to compile the basic hello.bas file. Can you help me with what I might be doing wrong? I included an "ls" of all the files in the main directory. Thank you!

(base) Montos-MacBook-Air:5200BAS_python-master monto$ ls
5200BAS possible improvements.txt basic documentation
5200bas-sources.zip dasm.exe
5200bask.bas examples
5200bask.py go.bat
5200basl.bas hello.bas
5200basl.py helloworld.bas
ASCIISET.INC inc
EQUATES.INC pm.bas
HEADER.INC readme.txt
How it works.txt
(base) Montos-MacBook-Air:5200BAS_python-master monto$ python 5200basl.py /D hello.bas
5200BAS Basic Compiler, version 1.97. Copyright 2001-2002 by Jeffry Johnston.

Compiling 32k ROM for DASM 2.12
Input file : hello.bas
Output file : hello.ASM
Pre-include : hello.2
Post-include: hello.1
Traceback (most recent call last):
File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2523, in 
result, asmFileName = main(args)
File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 198, in main
inFile = open(inFileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'hello.bas '
(base) Montos-MacBook-Air:5200BAS_python-master monto$

**Comment by scuttle130** [comment]
Thank you…. I’ll try it again! Sent from my iPhoneOn Sep 14, 2023, at 08:56, james7780 ***@***.***> wrote:﻿
 Looking at the error: "FileNotFoundError: [Errno 2] No such file or directory: 'hello.bas ' 

It looks like you typed an extra space after hello.bas when entering the command.





    On Thursday, September 14, 2023 at 05:54:02 AM GMT+2, scuttle130 ***@***.***> wrote:  

 

 





Thank you so much for creating a compiler to use 5200bas for MacOS! Below is error message I am getting from trying to compile the basic hello.bas file. Can you help me with what I might be doing wrong? I included an "ls" of all the files in the main directory. Thank you!



(base) Montos-MacBook-Air:5200BAS_python-master monto$ ls

5200BAS possible improvements.txt basic documentation

5200bas-sources.zip dasm.exe

5200bask.bas examples

5200bask.py go.bat

5200basl.bas hello.bas

5200basl.py helloworld.bas

ASCIISET.INC inc

EQUATES.INC pm.bas

HEADER.INC readme.txt

How it works.txt

(base) Montos-MacBook-Air:5200BAS_python-master monto$ python 5200basl.py /D hello.bas

5200BAS Basic Compiler, version 1.97. Copyright 2001-2002 by Jeffry Johnston.



Compiling 32k ROM for DASM 2.12

Input file : hello.bas

Output file : hello.ASM

Pre-include : hello.2

Post-include: hello.1

Traceback (most recent call last):

File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2523, in 

result, asmFileName = main(args)

File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 198, in main

inFile = open(inFileName, 'r')

FileNotFoundError: [Errno 2] No such file or directory: 'hello.bas '

(base) Montos-MacBook-Air:5200BAS_python-master monto$

**Comment by scuttle130** [comment]
You were right about the extra space.  For some reason, on line 127 `args.rstrip() `did not actually strip the last space.  I added 

`    args = args.strip(" “)`

on line 155.  And that fixed the extra space problem at the end of the filename.
