### ISSUE TITLE
No such file "INC\\KEYPAD.INC"

### ISSUE THREAD

**Issue by scuttle130** [james7780/5200BAS_python#2]
You were right about the extra space.  For some reason, on line 127 `args.rstrip()` did not actually strip the last space.  I added 

    args = args.strip(" “)

on line 155, but it found another problem.  There is a double “\” to dive into the inc directory and so the program can’t find the second directory.  I tried deleting a “\” from lines 

2415 (maybe 2414) 
`fileName = "INC\\" + fileName + ".INC"`

and line 2464 (maybe 2463)
`print ("Invalid include expression in INC\\", sFILENAME, ".INC")`

**and it caused the following error:**
(base) Montos-MacBook-Air:5200BAS_python-master monto$ python3 5200basl.py /16 /D hello
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2415
    fileName = "INC\" + fileName + ".INC"
                                         ^
SyntaxError: EOL while scanning string literal
(base) Montos-MacBook-Air:5200BAS_python-master monto$ 

**but with the double slash:**
(base) Montos-MacBook-Air:5200BAS_python-master monto$ python3 5200basl.py /16 /D hello
5200BAS Basic Compiler, version 1.97.  Copyright 2001-2002 by Jeffry Johnston.

Compiling 16k ROM for DASM 2.12
Input file  :  hello.BAS
Output file :  hello.ASM
Pre-include :  hello.2
Post-include:  hello.1
PARSING 2: TITLE "joystick test"
PARSING 4: AUTHOR "   (C) ANON 2112    "
PARSING 7: CLS
PARSING 8: PRINT "Hello World!"
Traceback (most recent call last):
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2525, in <module>
    result, asmFileName = main(args)
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 485, in main
    INCLUDEASM("KEYPAD")       # KEYPAD
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2484, in INCLUDEASM
    INCLUDEFILE(includeName)
  File "/Users/monto/Downloads/5200BAS_python-master/5200basl.py", line 2418, in INCLUDEFILE
    file = open(fileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'INC\\\KEYPAD.INC'
(base) Montos-MacBook-Air:5200BAS_python-master monto$

**Comment by scuttle130** [comment]
Here is the contents of the "inc" folder:

(base) Montos-MacBook-Air:5200BAS_python-master monto$ cd inc
(base) Montos-MacBook-Air:inc monto$ ls
\		crlf.inc	div8.inc	keypad.196	memcopy.inc	parse.dat	putmsi.inc	putspr.inc	vecttbl.inc
chkrow.inc	defervbi.196	down.inc	keypad.inc	moveup.inc	pos.inc		putmsl.inc	right.inc	y2k.inc
clearram.inc	defervbi.inc	input.inc	left.inc	mul8.inc	print.inc	putsph.inc	up.inc
cls.inc		div16.inc	joystick.inc	memarea.inc	muladd.inc	putmsh.inc	putspi.inc	vectors.dat
(base) Montos-MacBook-Air:inc monto$

**Comment by scuttle130** [comment]
Here is the contents of the "inc" folder:

(base) Montos-MacBook-Air:5200BAS_python-master monto$ cd inc
(base) Montos-MacBook-Air:inc monto$ ls
\		crlf.inc	div8.inc	keypad.196	memcopy.inc	parse.dat	putmsi.inc	putspr.inc	vecttbl.inc
chkrow.inc	defervbi.196	down.inc	keypad.inc	moveup.inc	pos.inc		putmsl.inc	right.inc	y2k.inc
clearram.inc	defervbi.inc	input.inc	left.inc	mul8.inc	print.inc	putsph.inc	up.inc
cls.inc		div16.inc	joystick.inc	memarea.inc	muladd.inc	putmsh.inc	putspi.inc	vectors.dat
(base) Montos-MacBook-Air:inc monto$

**Comment by scuttle130** [comment]
I tried removing the first slash and the program won't run.  I tried renaming the "inc" directory to "inc\" to try and trick it to look there, but no luck.  I copied the keyboard.inc file up into the master directory and named it "inc\\keyboard.inc" and that did not work.  For some reason its looking for a fileName "INC\\KEYBOARD.INC" and it cannot find it.  I also tried to strip the second "\", but that didn't work either.  My estimation is that its got too many "\" and can't find the subdirectory.  But don't really understand the rest of the code enough to see the "inc" directory is supposed to be somewhere else or if there is a parsing that will eventually remove the second "\" and then it will find the "inc" directory correctly.

**Comment by scuttle130** [comment]
SOLVED!!!  If guess for python in Windows, subdirectories use "\" to find them, but since "\" has special meaning in python, Windows users have to use "\\".  In all other platforms (like MacOS), python uses "/" for subdirectories.  On line 2415 (or 2414), I changed it to:

`fileName = "INC/" + fileName + ".INC"`

and it works.  But comes up with a new error....

**Comment by james7780** [comment]
I would have suggested changing the \ to a / , as the \ is a Windows thing.
