### ISSUE TITLE
DASM on MacOS

### ISSUE THREAD

**Issue by scuttle130** [james7780/5200BAS_python#3]
Not sure if its because the dasm included in the directory is a .exe file, and .exe files don't work on Mac, but it seems when it tries to execute this line, it errors out.  BUT!!! It creates the .asm file.  If you have dasm installed on your Mac already, and run the line 5200bas is trying to run `"dasm hello.asm -f3 -ohello.bin"` dasm will create the hello.bin file as its supposed too.  But it gives the following error:

```
hello.asm (100): error: Multi-line comment closed without open.

Unrecoverable error(s) in pass, aborting assembly!
Complete. (5)
```

BUT!!! Don't worry about that...it creates the hello.bin file anyways!  Which is the file you need to run on your 5200 emulator (like Jum52), and it runs JUST FINE!!!!

**Comment by scuttle130** [comment]
I think this program is awesome, and I can't wait to create some 5200bas on my mac now.  Thank you to James7780 for creating this!  I got it to work!

**Comment by james7780** [comment]
Thanks for the kind words, I'm glad you have got it working on Mac :)

It was supposed to be cross-platform, but I don't think I ever tested it on Mac (and maybe not Linux either :).

I agree with what Sebastian says on his page:
http://sebastianmihai.com/atari-5200-shooting-gallery.html

5200Bas is useful for writing simple games, or for learning how the 5200 works, but in any case to get any good results you have to know how the 5200 does it's graphics and sound.

**Comment by scuttle130** [comment]
I’m so glad you created this in the first place!  I will use it at face value. I have done a lot of studying to program the 2600, but the 5200 is my favorite. Anything that gets me a little closer to creating a 5200 game, and I am happy. I’m looking forward to playing around with this now!  Sent from my iPhoneOn Sep 18, 2023, at 09:55, james7780 ***@***.***> wrote:﻿
Thanks for the kind words, I'm glad you have got it working on Mac :)
It was supposed to be cross-platform, but I don't think I ever tested it on Mac (and maybe not Linux either :).
I agree with what Sebastian says on his page:
http://sebastianmihai.com/atari-5200-shooting-gallery.html
5200Bas is useful for writing simple games, or for learning how the 5200 works, but in any case to get any good results you have to know how the 5200 does it's graphics and sound.
